# Generated by Django 5.1.1 on 2024-10-15 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccsrepo_app', '0002_keyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manuscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('abstracts', models.TextField()),
                ('citations', models.TextField()),
                ('authors', models.CharField(max_length=255)),
                ('publication_date', models.DateField()),
                ('pdf_file', models.FileField(upload_to='manuscripts/')),
                ('status', models.CharField(default='pending', max_length=10)),
                ('allowed_student', models.BooleanField(default=False)),
                ('adviser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manuscripts', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccsrepo_app.batch')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccsrepo_app.category')),
                ('keywords', models.ManyToManyField(related_name='manuscripts', to='ccsrepo_app.keyword')),
                ('manuscript_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccsrepo_app.manuscripttype')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccsrepo_app.program')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_manuscripts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
