# Generated by Django 5.1.2 on 2024-11-07 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccsrepo_app', '0002_customuser_middle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageocrdata',
            name='image',
        ),
    ]
