# Generated by Django 5.1.2 on 2024-10-16 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccsrepo_app', '0003_manuscript'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscript',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ccsrepo_app.batch'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ccsrepo_app.category'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='keywords',
            field=models.ManyToManyField(null=True, related_name='manuscripts', to='ccsrepo_app.keyword'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='manuscript_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ccsrepo_app.manuscripttype'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ccsrepo_app.program'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_manuscripts', to=settings.AUTH_USER_MODEL),
        ),
    ]
