# Generated by Django 5.1.2 on 2024-11-07 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccsrepo_app', '0004_adviserstudentrelationship_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
