# Generated by Django 5.1.2 on 2024-10-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccsrepo_app', '0004_alter_manuscript_batch_alter_manuscript_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscript',
            name='keywords',
            field=models.ManyToManyField(related_name='manuscripts', to='ccsrepo_app.keyword'),
        ),
    ]
