# Generated by Django 5.1.2 on 2024-11-07 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccsrepo_app', '0005_manuscript_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscript',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
