# Generated by Django 5.1.2 on 2024-10-20 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccsrepo_app', '0006_alter_manuscript_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
