# Generated by Django 5.1.2 on 2024-11-08 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccsrepo_app', '0006_alter_manuscript_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscript',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
