# Generated by Django 5.1.2 on 2024-11-08 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccsrepo_app', '0008_alter_manuscript_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manuscript',
            name='citations',
        ),
    ]
