# Generated by Django 5.1.1 on 2024-10-14 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccsrepo_app', '0008_customuser_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AdviserStudentRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('adviser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adviser_relationships', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_relationships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='advises',
            field=models.ManyToManyField(blank=True, related_name='advised_by', through='ccsrepo_app.AdviserStudentRelationship', to=settings.AUTH_USER_MODEL),
        ),
    ]
