# Generated by Django 5.1.2 on 2024-11-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccsrepo_app', '0009_remove_manuscript_citations'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='upload_show',
            field=models.BooleanField(default=False),
        ),
    ]
