# Generated by Django 5.1.2 on 2024-10-29 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccsrepo_app', '0009_pageocrdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageOCRData',
        ),
    ]
