# Generated by Django 5.1.2 on 2024-10-29 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccsrepo_app', '0010_delete_pageocrdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageOCRData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_num', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_data', to='ccsrepo_app.manuscript')),
            ],
            options={
                'unique_together': {('manuscript', 'page_num')},
            },
        ),
    ]
