# Generated by Django 5.1.2 on 2024-11-08 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccsrepo_app', '0010_manuscript_upload_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manuscript',
            name='batch',
        ),
    ]
