# Generated by Django 5.1.2 on 2024-10-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccsrepo_app', '0011_pageocrdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageocrdata',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ocr_images/'),
        ),
    ]
