# Generated by Django 5.1.2 on 2024-11-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccsrepo_app', '0011_remove_manuscript_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscript',
            name='abstracts',
            field=models.TextField(blank=True, null=True),
        ),
    ]
