# Generated by Django 5.1.2 on 2024-10-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccsrepo_app', '0012_pageocrdata_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageocrdata',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='page_images/'),
        ),
    ]
