# Generated by Django 5.1.2 on 2024-11-08 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccsrepo_app', '0012_alter_manuscript_abstracts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscript',
            name='publication_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
