# Generated by Django 5.1.2 on 2024-11-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccsrepo_app', '0013_alter_manuscript_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='adviserstudentrelationship',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=10),
        ),
    ]
