# Generated by Django 5.1.2 on 2024-10-29 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccsrepo_app', '0014_rename_image_pageocrdata_image_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pageocrdata',
            old_name='image_file',
            new_name='image',
        ),
    ]
