# Generated by Django 5.1.2 on 2024-10-29 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccsrepo_app', '0015_rename_image_file_pageocrdata_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='extract_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
