# Generated by Django 5.1.2 on 2024-11-15 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccsrepo_app', '0015_manuscript_current_page_count_manuscript_page_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='ccsrepo_app.manuscript')),
            ],
            options={
                'unique_together': {('manuscript', 'keyword')},
            },
        ),
    ]
