# Generated by Django 5.1.2 on 2024-10-29 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccsrepo_app', '0016_manuscript_extract_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manuscript',
            name='extract_title',
        ),
    ]
