# Generated by Django 5.1.2 on 2024-11-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccsrepo_app', '0017_alter_keyword_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='keywords_extracted',
            field=models.BooleanField(default=False),
        ),
    ]
